//Dasboard Action Types
export const NEW_UPDATE_FETCH = "NEW_UPDATES_FETCH"
export const NEW_UPDATE_FETCH_SUCCESS = "NEW_UPDATES_FETCH_SUCCESS"
export const NEW_UPDATE_FETCH_ERROR = "NEW_UPDATES_FETCH_ERROR"
export const RECENT_UPDATE_FETCH = "RECENT_UPDATES_FETCH"
export const RECENT_UPDATE_FETCH_SUCCESS = "RECENT_UPDATES_FETCH_SUCCESS"
export const RECENT_UPDATE_FETCH_ERROR = "RECENT_UPDATES_FETCH_ERROR"

//Toast Action Types
export const SHOW_TOAST = "SHOW_TOAST"
export const CLOSE_TOAST = "CLOSE_TOAST"

//Form data Action Types
export const FETCH_INSTITUTE_TYPE = "FETCH_INSTITUTE_TYPE"
export const FETCH_INSTITUTE_TYPE_SUCCESS = "FETCH_INSTITUTE_TYPE_SUCCESS"
export const FETCH_INSTITUTE_TYPE_ERROR = "FETCH_INSTITUTE_TYPE_ERROR"
export const FETCH_YEAR = "FETCH_YEAR"
export const FETCH_YEAR_SUCCESS = "FETCH_YEAR_SUCCESS"
export const FETCH_YEAR_ERROR = "FETCH_YEAR_ERROR"
export const FETCH_ROUND = "FETCH_ROUND"
export const FETCH_ROUND_SUCCESS = "FETCH_ROUND_SUCCESS"
export const FETCH_ROUND_ERROR = "FETCH_ROUND_ERROR"

//List Action Types
export const FETCH_INSTITUTE_LIST = "FETCH_INSTITUTE_LIST"
export const FETCH_INSTITUTE_LIST_SUCCESS = "FETCH_INSTITUTE_LIST_SUCCESS"
export const FETCH_INSTITUTE_LIST_ERROR = "FETCH_INSTITUTE_LIST_ERROR"
export const FETCH_SEAT_MATRIX = "FETCH_SEAT_MATRIX"
export const FETCH_SEAT_MATRIX_SUCCESS = "FETCH_SEAT_MATRIX_SUCCESS"
export const FETCH_SEAT_MATRIX_ERROR = "FETCH_SEAT_MATRIX_ERROR"
export const FETCH_RANK_LIST = "FETCH_RANK_LIST"
export const FETCH_RANK_LIST_SUCCESS = "FETCH_RANK_LIST_SUCCESS"
export const FETCH_RANK_LIST_ERROR = "FETCH_RANK_LIST_ERROR"
