export const filter_choices={
    STATE_CHOICES:[
        'Andhra Pradesh',
        'Arunachal Pradesh',
        'Assam',
        'Bihar',
        'Chhattisgarh',
        'Goa',
        'Gujarat',
        'Haryana',
        'Himachal Pradesh',
        'Jammu & Kashmir ',
        'Jharkhand',
        'Karnataka',
        'Kerala',
        'Madhya Pradesh',
        'Maharashtra',
        'Manipur',
        'Meghalaya',
        'Mizoram',
        'Nagaland',
        'Orissa',
        'Punjab',
        'Rajasthan',
        'Sikkim',
        'Tamil Nadu',
        'Telangana',
        'Tripura',
        'Uttar Pradesh',
        'Uttarakhand',
        'West Bengal',
        'Andaman and Nicobar Islands',
        'Chandigarh','Chandigarh',
        'Dadra and Nagar Haveli',
        'Daman and Diu',
        'Lakshadweep',
        'National Capital Territory of Delhi',
        'Puducherry',
    ],
    INSTITUTE_CHOICES:[
        "Assam University, Silchar",                                                                                                     
        "Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior",                                          
        "Birla Institute of Technology, Mesra, Ranchi",                                                                                  
        "Central institute of Technology Kokrajar, Assam",                                                                               
        "Central University of Jammu",                                                                                                   
        "Central University of Rajasthan, Rajasthan",                                                                                    
        "Chhattisgarh Swami Vivekanada Technical University, Bhilai (CSVTU Bhilai)",                                                     
        "Dr. B R Ambedkar National Institute of Technology, Jalandhar",                                                                  
        "Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal",                                              
        "Gurukula Kangri Vishwavidyalaya, Haridwar",                                                                                     
        "HNB Garhwal University Srinagar (Garhwal)",                                                                                     
        "Indian Institute of Carpet Technology, Bhadohi",                                                                                
        "Indian Institute of Crop Processing Technology, Thanjavur, Tamilnadu",                                                          
        "Indian Institute of Engineering Science and Technology, Shibpur",                                                               
        "Indian Institute of Handloom Technology (IIHT), Varanasi",                                                                      
        "Indian Institute of Information Technology (IIIT) Dharwad",                                                                     
        "Indian Institute of Information Technology (IIIT) Kalyani, West Bengal",                                                        
        "Indian Institute of Information Technology (IIIT) Kilohrad, Sonepat, Haryana",                                                  
        "Indian Institute of Information Technology (IIIT) Kota, Rajasthan",                                                            
        "Indian Institute of Information Technology (IIIT) Kottayam",                                                                    
        "Indian Institute of Information Technology (IIIT) Nagpur",                                                                      
        "Indian Institute of Information Technology (IIIT) Pune",                                                                        
        "Indian Institute of Information Technology (IIIT) Ranchi",                                                                     
        "Indian Institute of Information Technology (IIIT) Una, Himachal Pradesh",                                                      
        "Indian Institute of Information Technology (IIIT), Sri City, Chittoor",                                                         
        "Indian Institute of Information Technology (IIIT), Vadodara, Gujrat",                                                           
        "Indian Institute of Information Technology Bhagalpur",                                                                          
        "Indian Institute of Information Technology Bhopal",                                                                             
        "Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh",                                     
        "Indian Institute of Information Technology Guwahati",                                                                           
        "Indian Institute of Information Technology Lucknow",                                                                            
        "Indian Institute of Information Technology Manipur",                                                                            
        "Indian Institute of Information Technology Surat",                                                                              
        "Indian Institute of Information Technology, Agartala",                                                                          
        "Indian Institute of Information Technology, Allahabad",                                                                         
        "Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram",                                              
        "Indian institute of information technology, Raichur, Karnataka",                                                                
        "Indian Institute of Information Technology, Tiruchirappalli",                                                                   
        "Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)",                                      
        "Indian Institute of Technology (BHU) Varanasi",                                                                                 
        "Indian Institute of Technology (ISM) Dhanbad",                                                                                 
        "Indian Institute of Technology Bhilai",                                                                                         
        "Indian Institute of Technology Bhubaneswar",                                                                                    
        "Indian Institute of Technology Bombay",                                                                                         
        "Indian Institute of Technology Delhi",                                                                                          
        "Indian Institute of Technology Dharwad",                                                                                        
        "Indian Institute of Technology Gandhinagar",                                                                                    
        "Indian Institute of Technology Goa",                                                                                            
        "Indian Institute of Technology Guwahati",                                                                                       
        "Indian Institute of Technology Hyderabad",                                                                                      
        "Indian Institute of Technology Indore",                                                                                         
        "Indian Institute of Technology Jammu",                                                                                          
        "Indian Institute of Technology Jodhpur",                                                                                       
        "Indian Institute of Technology Kanpur",                                                                                         
        "Indian Institute of Technology Kharagpur",                                                                                     
        "Indian Institute of Technology Madras",                                                                                         
        "Indian Institute of Technology Mandi",                                                                                         
        "Indian Institute of Technology Palakkad",                                                                                      
        "Indian Institute of Technology Patna",                                                                                        
        "Indian Institute of Technology Roorkee",                                                                                       
        "Indian Institute of Technology Ropar",                                                                                         
        "Indian Institute of Technology Tirupati",                                                                                       
        "Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar",                                              
        "Institute of Infrastructure, Technology, Research and Management-Ahmedabad",                                                
        "Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)",                             
        "International Institute of Information Technology, Bhubaneswar",                                                               
        "International Institute of Information Technology, Naya Raipur",                                                               
        "J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad",
        "Jawaharlal Nehru University, Delhi",                                                                                        
        "Malaviya National Institute of Technology Jaipur",                                                                             
        "Maulana Azad National Institute of Technology Bhopal",                                                                      
        "Mizoram University, Aizawl",                                                                                                  
        "Motilal Nehru National Institute of Technology Allahabad",                                                                     
        "National Institute of Advanced Manufacturing Technology, Ranchi",                                                             
        "National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)",                                        
        "National Institute of Food Technology Entrepreneurship and Management, Sonepat, Haryana",                                     
        "National Institute of Food Technology, Entrepreneurship and Management (NIFTEM) - Thanjavur",                                  
        "National Institute of Technology Agartala",                                                                                    
        "National Institute of Technology Arunachal Pradesh",                                                                           
        "National Institute of Technology Calicut",                                                                                      
        "National Institute of Technology Delhi",                                                                                        
        "National Institute of Technology Durgapur",                                                                                    
        "National Institute of Technology Goa",                                                                                         
        "National Institute of Technology Hamirpur",                                                                                    
        "National Institute of Technology Karnataka, Surathkal",                                                                        
        "National Institute of Technology Meghalaya",                                                                                    
        "National Institute of Technology Nagaland ",                                                                                    
        "National Institute of Technology Patna",                                                                                      
        "National Institute of Technology Puducherry",                                                                                 
        "National Institute of Technology Raipur",                                                                                    
        "National Institute of Technology Sikkim",                                                                             
        "National Institute of Technology, Andhra Pradesh",                                                                             
        "National Institute of Technology, Jamshedpur",                                                                                 
        "National Institute of Technology, Kurukshetra",                                                                                 
        "National Institute of Technology, Manipur",                                                                                   
        "National Institute of Technology, Mizoram",                                                                                   
        "National Institute of Technology, Rourkela",                                                                                   
        "National Institute of Technology, Silchar",                                                                                   
        "National Institute of Technology, Srinagar",                                                                                  
        "National Institute of Technology, Tiruchirappalli",                                                                            
        "National Institute of Technology, Uttarakhand",                                                                                
        "National Institute of Technology, Warangal",                                                                                   
        "North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar), Arunachal Pradesh",                      
        "North-Eastern Hill University, Shillong",                                                                                      
        "Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur",                           
        "Puducherry Technological University, Puducherry",                                                                               
        "Punjab Engineering College, Chandigarh",                                                                                       
        "Rajiv Gandhi Institute of Information Technology Amethi (A Campus of IIIT Allahabad)",                                          
        "Sant Longowal Institute of Engineering and Technology",                                                                        
        "Sardar Vallabhbhai National Institute of Technology, Surat",                                                                   
        "School of Engineering, Tezpur University, Napaam, Tezpur",                                                                     
        "School of Planning & Architecture, Bhopal",                                                                                     
        "School of Planning & Architecture, New Delhi",                                                                                 
        "School of Planning & Architecture: Vijayawada",                                                                                 
        "Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir",                                                                    
        "University of Hyderabad",                                                                                                      
        "Visvesvaraya National Institute of Technology, Nagpur",               
    ],
    CATEGORY_CHOICES:["GEN-EWS(PwD)","GEN-EWS","General PwD","General","SC","ST","SC PwD","ST PwD","OBC-NCL","OBC-NCL(PwD)"],
    QUOTA_CHOICES:['AI','HS','OS','GO','JK','LA','AP'],
    SEAT_POOL_CHOICES:['Gender-Neutral','Female_only'],
    BRANCH_CHOICES:[
        "Aerospace Engineering",                                                                                                                                        
        "Agricultural and Food Engineering",                                                                                                                            
        "Agricultural and Food Engineering with M.Tech. in any of the listed specializations",                                                                          
        "Agricultural Engineering",                                                                                                                                     
        "Applied Geology",                                                                                                                                              
        "Applied Geophysics",                                                                                                                                           
        "Applied Mathematics",                                                                                                                                          
        "Architecture",                                                                                                                                                 
        "Architecture, Town and Regional Planning",                                                                                                                     
        "Artificial Intelligence",                                                                                                                                      
        "Artificial Intelligence and Data Science",                                                                                                                    
        "Artificial Intelligence and Machine Learning",                                                                                                                 
        "B. Tech. Computer Science and Engineering and M. Tech. Computer Science and Engineering with specialization in Systems Design",                                
        "B. Tech. Electronics and Communication Engineering and M. Tech. Electronics and Communication Engineering with specialization in Communication Systems Design",
        "B. Tech. Electronics and Communication Engineering and M. Tech. Electronics and Communication Engineering with specialization in VLSI Design",                 
        "B. Tech. Mechanical Engineering and M. Tech. in Mechanical Engineering with specialization in Product Design",                                                 
        "B. Tech. Mechanical Engineering and M. Tech. Mechanical Engineering with specialization in Advanced Manufacturing",                                            
        "B.Tech (Information Technology) and MBA /M.Tech (Information Technology)",                                                                                     
        "Bio Engineering",                                                                                                                                             
        "Bio Medical Engineering",                                                                                                                                      
        "Bio Technology",                                                                                                                                               
        "Biochemical Engineering and Biotechnology",                                                                                                                    
        "Biochemical Engineering with M.Tech. in Biochemical Engineering and Biotechnology",                                                                            
        "Bioengineering with M.Tech in Biomedical Technology",                                                                                                          
        "Biological Engineering",                                                                                                                                       
        "Biological Sciences",                                                                                                                                          
        "Biological Sciences and Bioengineering",                                                                                                                       
        "Biomedical Engineering",                                                                                                                                       
        "Biosciences and Bioengineering",                                                                                                                               
        "Biotechnology",                                                                                                                                                
        "Biotechnology and Biochemical Engineering",                                                                                                                    
        "Biotechnology and Bioinformatics",                                                                                                                             
        "BS in Mathematics",                                                                                                                                            
        "Carpet and Textile Technology",                                                                                                                                
        "Ceramic Engineering",                                                                                                                                          
        "Ceramic Engineering and M.Tech Industrial Ceramic",                                                                                                            
        "Chemical and Biochemical Engineering",                                                                                                                         
        "Chemical Engineering",                                                                                                                                         
        "Chemical Engineering (Plastic and Polymer)",                                                                                                                   
        "Chemical Science and Technology",                                                                                                                              
        "Chemical Sciences",                                                                                                                                            
        "Chemistry",                                                                                                                                                    
        "Chemistry with Specialization",                                                                                                                                
        "Civil and Infrastructure Engineering",                                                                                                                         
        "Civil Engineering",                                                                                                                                            
        "Civil Engineering and M. Tech. in Structural Engineering",                                                                                                     
        "Civil Engineering and M.Tech in Transportation Engineering",                                                                                                   
        "Civil Engineering and M.Tech in Water Resources",                                                                                                              
        "Civil Engineering and M.Tech. in Environmental Engineering",                                                                                                   
        "Civil Engineering with any of the listed specialization",                                                                                                      
        "Civil Engineering with Specialization in Construction Technology and Management",                                                                              
        "Computational and Data Science",                                                                                                                               
        "Computational Engineering",                                                                                                                                    
        "Computational Mathematics",                                                                                                                                    
        "Computer Engineering",                                                                                                                                         
        "Computer Science",                                                                                                                                             
        "Computer Science & Engineering",                                                                                                                               
        "Computer Science and Artificial Intelligence",                                                                                                                 
        "Computer Science and Business",                                                                                                                                
        "Computer Science and Engineering",                                                                                                                             
        "Computer Science and Engineering (with Specialization of Data Science and Artificial Intelligence)",                                                           
        "Computer Science and Engineering and M.Tech Computer Science",                                                                                                 
        "Computer Science and Engineering and M.Tech in Information Security",                                                                                          
        "Computer Science and Engineering with Major in Artificial Intelligence",                                                                                       
        "Computer Science and Engineering with specialization in Artificial Intelligence and Data Science",                                                             
        "Computer Science and Engineering with specialization in Cyber Security",                                                                                       
        "Computer Science and Engineering with Specialization in Data Science",                                                                                         
        "Computer Science and Technology",                                                                                                                              
        "Computer Science Engineering (Artificial Intelligence)",                                                                                                       
        "Computer Science Engineering (Artificial lntelligence and Machine Learning)",                                                                                  
        "Computer Science Engineering (Data Science and Analytics)",                                                                                                    
        "Computer Science Engineering (Data Science)",                                                                                                                  
        "Computer Science Engineering (Human Computer lnteraction and Gaming Technology)",                                                                              
        "Data Science and Artificial Intelligence",                                                                                                                     
        "Data Science and Engineering",                                                                                                                                 
        "Design",                                                                                                                                                       
        "Earth Sciences",                                                                                                                                              
        "Economics",                                                                                                                                                   
        "Electrical and Electronics Engineering",                                                                                                                       
        "Electrical and Instrumentation Engineering",                                                                                                                   
        "Electrical Engineering",                                                                                                                                       
        "Electrical Engineering (IC Design and Technology)",                                                                                                            
        "Electrical Engineering (Power and Automation)",                                                                                                                
        "Electrical Engineering and M.Tech Control and Automation",                                                                                                     
        "Electrical Engineering and M.Tech Electronic Systems and Communications",                                                                                      
        "Electrical Engineering and M.Tech Power Electronics and Drives",                                                                                               
        "Electrical Engineering with M.Tech. in any of the listed specializations",                                                                                     
        "Electrical Engineering with M.Tech. in Communications and Signal Processing",                                                                                  
        "Electrical Engineering with M.Tech. in Microelectronics",                                                                                                      
        "Electrical Engineering with M.Tech. in Power Electronics",                                                                                                     
        "Electrical Engineering with Specialization In Power System Engineering",                                                                                       
        "Electronics & Communication Engineering",                                                                                                                      
        "Electronics and Communication Engineering",                                                                                                                    
        "Electronics and Communication Engineering - Design and Manufacturing + M. Tech VLSI & Electronic System Design",                                               
        "Electronics and Communication Engineering (Avionics)",                                                                                                        
        "Electronics and Communication Engineering (Internet of Things)",                                                                                               
        "Electronics and Communication Engineering (Under Flexible Academic Program)",                                                                                  
        "Electronics and Communication Engineering (with Specialization of Embedded Systems and Internet of Things)",                                                   
        "Electronics and Communication Engineering and M.Tech (ECE) Spl. (Micro Electronics)",                                                                          
        "Electronics and Communication Engineering and M.Tech Communication and Network",                                                                               
        "Electronics and Communication Engineering and M.Tech. Bio-Medical Engineering ",                                                                               
        "Electronics and Communication Engineering and MBA (Information Technology)",                                                                                   
        "Electronics and Communication Engineering with specialization in Design and Manufacturing",                                                                    
        "Electronics and Communication Engineering with specialization in Design and Manufacturing + M. Tech - Signal Processing and Communication Systems Design",     
        "Electronics and Communication Engineering with specialization in Design and Manufacturing + M. Tech - VLSI and Electronic Systems Design",                     
        "Electronics and Communication Engineering with Specialization in Microelectronics and VLSI System Design",                                                     
        "Electronics and Communication Engineering with specialization in VLSI and Embedded Systems",                                                                   
        "Electronics and Electrical Communication Engineering",                                                                                                         
        "Electronics and Electrical Communication Engineering with M.Tech. in any of the listed specializations",                                                      
        "Electronics and Electrical Engineering",                                                                                                                       
        "Electronics and Instrumentation Engineering",                                                                                                                 
        "Electronics and Instrumentation Engineering and M.Tech VLSI Design and Embedded",                                                                              
        "Electronics and Telecommunication Engineering",                                                                                                                
        "Electronics Engineering",                                                                                                                                      
        "Electronics Engineering - Design and Manufacturing",                                                                                                           
        "Electronics Engineering (D and M) and M.Tech Signal Processing and Communication System Design",                                                               
        "Electronics System Engineering",                                                                                                                               
        "Energy Engineering",                                                                                                                                           
        "Energy Engineering with M.Tech. in Energy Systems Engineering",                                                                                                
        "Engineering and Computational Mechanics",                                                                                                                      
        "Engineering Design",                                                                                                                                           
        "Engineering Physics",                                                                                                                                          
        "Engineering Physics and M.Tech. with specialization in Nano Science",                                                                                          
        "Engineering Science",                                                                                                                                          
        "Environmental Engineering",                                                                                                                                    
        "Environmental Science and Engineering",                                                                                                                        
        "Exploration Geophysics",                                                                                                                                       
        "Food Engineering and Technology",                                                                                                                              
        "Food Process Engineering",                                                                                                                                    
        "Food Processing Engineering",                                                                                                                                 
        "Food Technology",                                                                                                                                             
        "Food Technology and Management",                                                                                                                               
        "Geological Technology",                                                                                                                                       
        "Geophysical Technology",                                                                                                                                       
        "Handloom and Textile Technology",                                                                                                                             
        "Industrial and Production Engineering",                                                                                                                       
        "Industrial and Systems Engineering",                                                                                                                          
        "Industrial and Systems Engineering with M.Tech. in Industrial and Systems Engineering and Management",                                                         
        "Industrial Chemistry",                                                                                                                                        
        "Industrial Design",                                                                                                                                            
        "Information Technology",                                                                                                                                       
        "Information Technology (Under Flexible Academic Program)",                                                                                                     
        "Information Technology and M.Tech (Information Technology) Spl. (Cyber Law and Information Security)",                                                         
        "Information Technology and M.Tech (Information Technology) Spl. (Human Computer Interaction)",                                                                 
        "Information Technology and M.Tech (Information Technology) Spl. (Intellegent System)",                                                                         
        "Information Technology and M.Tech (Information Technology) Spl. Bio-Informatics",                                                                              
        "Information Technology and M.Tech (Information Technology) Spl. Robotics",                                                                                     
        "Information Technology and M.Tech (Information Technology) Spl. Software Engineering",                                                                         
        "Information Technology and M.Tech (Information Technology) Spl. Wireless Communication Engineering",                                                           
        "Information Technology and MBA (Information Technology)",                                                                                                      
        "Information Technology-Business Informatics",                                                                                                                  
        "Instrumentation and Control Engineering",                                                                                                                     
        "Instrumentation Engineering",                                                                                                                                  
        "Integrated B. Tech.(IT) and M. Tech (IT)",                                                                                                                     
        "Integrated B. Tech.(IT) and MBA",                                                                                                                             
        "Interdisciplinary Sciences (5 Years, Bachelor of Science and Master of Science (Dual Degree))",                                                                
        "Life Science",                                                                                                                                                 
        "Manufacturing Engineering",                                                                                                                                    
        "Manufacturing Science and Engineering",                                                                                                                        
        "Manufacturing Science and Engineering with M.Tech. in Industrial and Systems Engineering and Management",                                                      
        "Material Science",                                                                                                                                             
        "Material Science and Engineering",                                                                                                                            
        "Materials and Metallurgical Engineering",                                                                                                                     
        "Materials Engineering",                                                                                                                                       
        "Materials Science and Engineering",                                                                                                                           
        "Materials Science and Metallurgical Engineering",                                                                                                              
        "Materials Science and Technology",                                                                                                                            
        "Mathematics",                                                                                                                                                  
        "Mathematics & Computing",                                                                                                                                      
        "Mathematics and Computing",                                                                                                                                   
        "Mathematics and Computing Technology",                                                                                                                        
        "Mathematics and Data Science",                                                                                                                                 
        "Mathematics and Scientific Computing",                                                                                                                         
        "Mechanical Engineering",                                                                                                                                      
        "Mechanical Engineering (Manuacturing Engineering)",                                                                                                            
        "Mechanical Engineering (Welding Technology)",                                                                                                                  
        "Mechanical Engineering and M. Tech. in Mechanical System Design",                                                                                             
        "Mechanical Engineering and M. Tech. in Thermal Science & Engineering",                                                                                        
        "Mechanical Engineering and M.Tech Mechatronics and Automation",                                                                                               
        "Mechanical Engineering and M.Tech. in Computer Integrated Manufacturing",                                                                                     
        "Mechanical Engineering with M.Tech. in any of the listed specializations",                                                                                     
        "Mechanical Engineering with M.Tech. in Manufacturing Engineering",                                                                                             
        "Mechanical Engineering with specialization in Design and Manufacturing",                                                                                      
        "Mechanical Engineering with specialization in Design and Manufacturing + M. Tech - Advanced Manufacturing",                                                   
        "Mechanical Engineering with specialization in Design and Manufacturing + M. Tech - Product Design",                                                            
        "Mechanical Engineering with Specialization in Manufacturing and Industrial Engineering",                                                                      
        "Mechanical Engineering with specialization in Smart Manufacturing",                                                                                           
        "Mechanical Engineering- Design and Manufacturing",                                                                                                            
        "Mechatronics Engineering",                                                                                                                                    
        "Metallurgical and Materials Engineering",                                                                                                                      
        "Metallurgical and Materials Engineering and M.Tech. in Materials Science and Engineering",                                                                     
        "Metallurgical Engineering",                                                                                                                                    
        "Metallurgical Engineering & Materials Science",                                                                                                                
        "Metallurgical Engineering and Materials Science",                                                                                                              
        "Metallurgical Engineering and Materials Science with M.Tech. in Ceramics and Composites",                                                                      
        "Metallurgical Engineering and Materials Science with M.Tech. in Metallurgical Process Engineering",                                                            
        "Metallurgy and Materials Engineering",                                                                                                                        
        "Mineral and Metallurgical Engineering",                                                                                                                        
        "Mineral Engineering",                                                                                                                                          
        "Mineral Engineering with M.Tech in Mineral Engineering",                                                                                                       
        "Mining Engineering",                                                                                                                                           
        "Mining Machinery Engineering",                                                                                                                                 
        "Mining Safety Engineering",                                                                                                                                    
        "Naval Architecture and Ocean Engineering",                                                                                                                     
        "Ocean Engineering and Naval Architecture",                                                                                                                     
        "Petroleum Engineering",                                                                                                                                        
        "Pharmaceutical Engineering & Technology",                                                                                                                     
        "Pharmaceutics",                                                                                                                                                
        "Physics",                                                                                                                                                      
        "Physics with Specialization",                                                                                                                                 
        "Planning",                                                                                                                                                    
        "Polymer Science and Engineering",                                                                                                                              
        "Production and Industrial Engineering",                                                                                                                        
        "Production Engineering",                                                                                                                                      
        "Quality Engineering Design and Manufacturing",                                                                                                                 
        "Quantitative Economics & Data Science",                                                                                                                        
        "Smart Manufacturing",                                                                                                                                          
        "Statistics and Data Science",                                                                                                                                 
        "Textile Technology",                                                                                                                                           
    ],

    DEGREE_CHOICES:[
        "B. Tech / B. Tech (Hons.)",                               
        "B.Tech. + M.Tech./MS (Dual Degree)",                      
        "Bachelor and Master of Pharmaceutics(Dual Degree)",       
        "Bachelor and Master of Technology (Dual Degree)",        
        "Bachelor of Architecture",                               
        "Bachelor of Design",                                      
        "Bachelor of Pharmaceutics",                               
        "Bachelor of Planning",                                    
        "Bachelor of Science",                                     
        "Bachelor of Science and Master of Science (Dual Degree)", 
        "Bachelor of Technology",                                 
        "Bachelor of Technology and MBA (Dual Degree)",            
        "Integrated B. Tech. and M. Tech. /MBA",                   
        "Integrated Master of Science",                            
        "Integrated Master of Technology",                        
        "Integrated Masters in Technology",                       
    ],
    DURATION_CHOICES:[
        "4 Years",
        "5 Years",
    ]


}
